CREATE TABLE TB_USUARIOS (
    ID LONG PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(255)
);

CREATE TABLE TB_ENDERECOS (
    ID LONG PRIMARY KEY AUTO_INCREMENT,
    CEP VARCHAR(255),
    RUA VARCHAR(255),
    NUMERO INT,
    USUARIO_ID LONG REFERENCES TB_USUARIOS(ID)
)